### ISSUE TITLE
Camera Widget not working.

### ISSUE THREAD

**Issue by JamesKennewell** [tjntomas/HADashboard-widgets#18]
i tried to setup the camera widget but i cant seam to get a stream to work.

my camera streams to HA fine and i can see it in the lovelace dashboard but i cant get to to show in HADashboard

my cameras.yaml`frontdoor:
  widget_type: camerastream
  entity: camera.front_door
  title: My Camera
  base_url: "http://192.168.1.235:8123"  
  # e.g. "https://my_duck_dns_domain.duckdns.org:8123" or "http://192.168.1.20:8123"
  log: 1  # optional. Will print some log info in the console for debugging purposes if set to 1.
  
layout:
  - frontdoor(2x2)`

My cameras.dash

`#
# Main arguments, all optional
#
title: Camera Panel
widget_dimensions: [131, 117]
widget_margins: [2, 2]
columns: 6

layout:
    - include: cameras`

and my configuration.yaml for the camera
`camera:
  - platform: generic
    name: Front Door
    still_image_url: https://media.bunnings.com.au/Product-384x384/7902858f-9f9f-4879-993b-3dd4ce53396f.png        
    stream_source: rtsp://192.168.1.137/user=username&password=password&channel=1&stream=0.sdp?`

**Comment by tjntomas** [comment]
Do you see any errors in the brower javascript console?

**Comment by JamesKennewell** [comment]
I actually got it working a few hours ago. On changing the entity to a ffmpeg insted of a generic type. 

But i don't remember seeing any errors

**Comment by tjntomas** [comment]
Ok, great!
